# coding: utf-8

"""
    Payment Processor Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paymentprocessor.api.paymentprocessor_api import PaymentprocessorApi


class TestPaymentprocessorApi(unittest.TestCase):
    """PaymentprocessorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentprocessorApi()

    def tearDown(self) -> None:
        pass

    def test_authorize_payment(self) -> None:
        """Test case for authorize_payment

        Authorize Payment
        """
        pass

    def test_create_payment_method(self) -> None:
        """Test case for create_payment_method

        Create Payment Method
        """
        pass

    def test_finalize_payment(self) -> None:
        """Test case for finalize_payment

        Finalize Payment
        """
        pass

    def test_get_available_payment_method(self) -> None:
        """Test case for get_available_payment_method

        Get Available Payment Method
        """
        pass

    def test_get_payment_method(self) -> None:
        """Test case for get_payment_method

        Get Payment Method
        """
        pass

    def test_get_payment_method_configuration(self) -> None:
        """Test case for get_payment_method_configuration

        Get Payment Method Configuration
        """
        pass

    def test_init_payment(self) -> None:
        """Test case for init_payment

        Init Payment
        """
        pass

    def test_list_available_payment_methods(self) -> None:
        """Test case for list_available_payment_methods

        List Available Payment Methods
        """
        pass

    def test_list_payment_methods(self) -> None:
        """Test case for list_payment_methods

        List Payment Methods
        """
        pass

    def test_perform_payment(self) -> None:
        """Test case for perform_payment

        Perform Payment
        """
        pass

    def test_perform_refund(self) -> None:
        """Test case for perform_refund

        Perform Refund
        """
        pass

    def test_update_payment(self) -> None:
        """Test case for update_payment

        Update Payment
        """
        pass

    def test_update_payment_method(self) -> None:
        """Test case for update_payment_method

        Update Payment Method
        """
        pass

    def test_void_payment(self) -> None:
        """Test case for void_payment

        Void Payment
        """
        pass


if __name__ == '__main__':
    unittest.main()
