# coding: utf-8

"""
    Payment Processor Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from paymentprocessor.models.condition_action import ConditionAction

class TestConditionAction(unittest.TestCase):
    """ConditionAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConditionAction(self):
        """Test ConditionAction"""
        # inst = ConditionAction()

if __name__ == '__main__':
    unittest.main()
