# coding: utf-8

"""
    Payment Processor Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from paymentprocessor.models.paymentprocessor_transaction_type import PaymentprocessorTransactionType

class TestPaymentprocessorTransactionType(unittest.TestCase):
    """PaymentprocessorTransactionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentprocessorTransactionType(self):
        """Test PaymentprocessorTransactionType"""
        # inst = PaymentprocessorTransactionType()

if __name__ == '__main__':
    unittest.main()
